### ISSUE TITLE
[icon] 请求新增“无障碍”（Accessibility）图标

### ISSUE THREAD

**Issue by ArcticFoxPro** [Tencent/tdesign-icons#104]
### 这个功能解决了什么问题

请求新增“无障碍”（Accessibility）图标，可用于涉及无障碍业务的标识。

可参考同类图标：

| 微软 Segoe Fluent Icon | Google Material Symbol | Apple SF Symbol | HUAWEI HarmonyOS Symbol |
| --- | --- | --- | --- |
| ![](https://github.com/user-attachments/assets/6ba51213-f775-43b2-a2ff-d471f3f78fec) | ![](https://github.com/user-attachments/assets/971ff268-ceb7-438b-a948-89a6de5283b3) | ![](https://github.com/user-attachments/assets/5c452c82-b482-4a08-8907-e5456e0c36c9) | ![](https://github.com/user-attachments/assets/6e6db8a9-bec8-47fa-a2a8-bd1def0d2b87) |

### 你建议的方案是什么

无

此外，希望此仓库单独添加一个新图标请求 Issue 模板，而非仅有“反馈 Bug”“反馈新功能”模板。

**Comment by uyarn** [comment]
好的

**Comment by uyarn** [comment]
https://github.com/Tencent/tdesign-icons/commit/b1b6ace72896a5a5ff942828dcf8facfa74685e6
