### ISSUE TITLE
[t-icon] 搜索图标不容易匹配想要的，建议：能否引入 AI 搜索，可按各种语义搜索图标？

### ISSUE THREAD

**Issue by vikyd** [Tencent/tdesign-icons#109]
### 这个功能解决了什么问题

如题

### 你建议的方案是什么

能否引入 AI 搜索，可按多种语义搜索图标？

**Comment by uyarn** [comment]
已经补充了关键词的搜索功能，可以体验一下，如果还有觉得可以改进的问题可以讨论下

**Comment by yinrenwangwei** [comment]
https://github.com/Tencent/tdesign-icons/issues/109#issuecomment-2328510363

**Comment by yinrenwangwei** [comment]
> 已经补充了关键词的搜索功能，可以体验一下，如果还有觉得可以改进的问题可以讨论下

https://github.com/Tencent/tdesign-icons/blob/develop/packages/view/src/manifest.js在官方文档中找到的‘图标仓库’，看着github上确实有中文检索功能，但是安装了0.3.0以上版本之后manifest中并没有对应的中文注释，都是类似于{stem: 'accessibility-filled', icon: 'AccessibilityFilled'}的对象，请问这个中文检索的功能是否可用，如果可用，是版本有问题吗？如果还没有完善此功能，请问什么时候可以支持此功能
