### ISSUE TITLE
[icon] 希望添加一个退出放大的图标

### ISSUE THREAD

**Issue by SaberA1ter** [Tencent/tdesign-icons#36]
### 这个功能解决了什么问题

在一个客户端应用中，很多时候会有放大、退出放大这个功能（详见右上角），在已有 icon 中存在 rectangle 这一个放大功能的 icon，却难找到一个常规的退出放大的 icon（两个方形叠放的效果？可见 window 应用右上角的放大和退出放大），我希望能保持 icon 风格一致（个人项目，莫得UI，不会画图），又希望不为了这一个图标而为项目增加更多的依赖负担。

### 你建议的方案是什么

我感觉这个 icon 属于客户端应用开发中非常容易会被使用到的 icon，希望能够添加这一个 icon 以满足需求（tdesign-icons-vue-next）。。。不知道这个希望会不会显得不太合适

**Comment by uyarn** [comment]
@SaberA1ter 好的 图标会一直增加的 有需要且合理的需求我们就会新增

**Comment by uyarn** [comment]
已在tdesign-icons-vue-next@0.1.5中新增
