### ISSUE TITLE
[ICON] 锁定图标可识别度不高

### ISSUE THREAD

**Issue by ouyoungs** [Tencent/tdesign-icons#93]
### 这个功能解决了什么问题

 lock-on  / lock-off  在页面上实际使用的时候，特别在状态切换的时候，很难肉眼分辨区别。

![Snipaste_2024-05-29_18-02-01](https://github.com/Tencent/tdesign-vue-next/assets/53481783/5f781895-3c25-40aa-9fd3-cfb6297799fe)

### 你建议的方案是什么

建议修改

**Comment by uyarn** [comment]
@ouyoungs 感谢反馈 @DOUBLE-DENG 是我们的设计同学 已经修改了图标 看看是否更清晰一些
<img width="1117" alt="企业微信截图_cd9f5b4e-a952-4e23-97bc-7462c6b327b5" src="https://github.com/Tencent/tdesign-icons/assets/26377630/03514496-72c5-4eb8-9392-c02a2a843cfa">

**Comment by ouyoungs** [comment]
这样应该在小图标情况下， 点击切换锁定状态的时候，容易分辨一些了。

**Comment by DOUBLE-DENG** [comment]
> 这样应该在小图标案情况下，点击切换锁定状态的时候，容易选择一些了。

已更新，感谢反馈

**Comment by uyarn** [comment]
https://github.com/Tencent/tdesign-icons/pull/97
